package com.zw.netty.facade.dto;
import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Agency extends AgencyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.collacctnbr
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private String collacctnbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.collacctname
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private String collacctname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.amt
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private BigDecimal amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.flag
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.gmt_create
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.gmt_modified
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.repayone
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private String repayone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cb_ae_agency.repaytwo
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    private String repaytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.collacctnbr
     *
     * @return the value of cb_ae_agency.collacctnbr
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public String getCollacctnbr() {
        return collacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.collacctnbr
     *
     * @param collacctnbr the value for cb_ae_agency.collacctnbr
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setCollacctnbr(String collacctnbr) {
        this.collacctnbr = collacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.collacctname
     *
     * @return the value of cb_ae_agency.collacctname
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public String getCollacctname() {
        return collacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.collacctname
     *
     * @param collacctname the value for cb_ae_agency.collacctname
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setCollacctname(String collacctname) {
        this.collacctname = collacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.amt
     *
     * @return the value of cb_ae_agency.amt
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.amt
     *
     * @param amt the value for cb_ae_agency.amt
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.flag
     *
     * @return the value of cb_ae_agency.flag
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.flag
     *
     * @param flag the value for cb_ae_agency.flag
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.gmt_create
     *
     * @return the value of cb_ae_agency.gmt_create
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.gmt_create
     *
     * @param gmtCreate the value for cb_ae_agency.gmt_create
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    protected void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.gmt_modified
     *
     * @return the value of cb_ae_agency.gmt_modified
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.gmt_modified
     *
     * @param gmtModified the value for cb_ae_agency.gmt_modified
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    protected void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.repayone
     *
     * @return the value of cb_ae_agency.repayone
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public String getRepayone() {
        return repayone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.repayone
     *
     * @param repayone the value for cb_ae_agency.repayone
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setRepayone(String repayone) {
        this.repayone = repayone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cb_ae_agency.repaytwo
     *
     * @return the value of cb_ae_agency.repaytwo
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public String getRepaytwo() {
        return repaytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cb_ae_agency.repaytwo
     *
     * @param repaytwo the value for cb_ae_agency.repaytwo
     *
     * @mbg.generated Tue Jan 29 22:12:11 CST 2019
     */
    public void setRepaytwo(String repaytwo) {
        this.repaytwo = repaytwo;
    }
    
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}